const template = {
  es: {
    name: 'txn-payment-ecommerce-receipt-es',
    subject: 'Recibo de pago Clip por: ${{amount}}',
  },
  data: {
    assetsUrl: 'https://dev-ses-email-templates-assets.s3.amazonaws.com',
    consumer_email: 'client@test.com',
    concept_message: 'Compra de productos',
    merchant_name: 'Ecommerce Payment test',
    merchant_id: '65eb8826-5848-4255-a5f7-14426a72f663',
    transaction_id: '6ac77f63-f1bf-4642-b95d-ee5b2718c93e',
    brand_img: 'receipt-cardbrand-mc.png',
    address1: '1234 Sesame Street',
    address2: 'Canada',
    colony: '12',
    municipality: 'Draper',
    state: 'UT',
    country: 'Mexico',
    postal_code: '84020',
    amount: '995.00',
    currency: 'MXN',
    card_no: '9112',
    order_id: '917957858659',
    auth_code: '222222',
    receipt_num: 'eJzO8CC',
    tip: '0.00',
    amountnotip: '995.00',
    card_label: 'MASTERCARD',
    processor_name: 'CLIPMX',
    issuer: 'Banamex',
    affiliation: '11223344',
    ice: 'ICE',
    auth_code_text: 'Approved by Banorte',
    payment_date: 'Mar 26 2020',
    payment_time: '11:02:35 AM',
    trx_id: '12345',
    brand: 'MC',
    term: 3,
  },
};

module.exports = locale => ({
  data: template.data,
  ...template[locale],
});
