const list = [
  // "agp-automation-dat-files",
  // "agp-automation-dat-files-update-me",
  // "agp-subaffiliation-monitor-dat-files",
  // "amex-disputes-optblue",
  // "bank-account-change-confirmation",
  "bank-account-change-to-be-removed",
  // "bank-account-change-updated",
  // "bank-account-change-validation",
  // "catalog-pilot-invitation",
  // "catalog-pilot-invitation-confirmation",
  // "commissionist-approval-required",
  // "commissionist-comodato-expiration",
  // "commissionist-delivered",
  // "commissionist-office-delivery",
  // "commissionist-request-rejected",
  // "commissionist-sample-renewal",
  // "commissionist-shipping",
  // "confirm-account",
  "customer360-password-reset",
  // "dependabot-report",
  // "ecommerce-openpay-confirmation",
  // "four-transactions-1",
  // "four-transactions-2",
  // "four-transactions-3",
  // "four-transactions-4",
  // "h2h-finance-automatic-disb",
  // "h2h-finance-automatic-disb-banorte",
  // "h2h-finance-automatic-disb-no-payments",
  // "h2h-finance-automatic-disb-warn",
  // "h2h-finance-disb",
  // "h2h-finance-disb-dsp",
  // "h2h-finance-disb-warn",
  // "h2h-finance-disbursements",
  // "h2h-finance-dsb-paid-error-review",
  // "h2h-finance-dsb-paid-error-review-approval",
  // "h2h-no-bank-account-merchant",
  // "h2h-pymt-fail-merchant",
  // "h2h-pymt-sent-merchant",
  "loans-account-status",
  // "loans-deposit-confirmation-mrp",
  //  "loans-finance-reports",
  // "loans-internal-reports",
  // "loans-preapproval-approved-mrp",
  // "loans-preapproval-invitation-clip",
  // "loans-preapproval-invitation-mrp",
  // "loans-preapproval-invitation-mrp-button-at-bottom",
  // "loans-preapproval-invitation-mrp-button-at-middle",
  // "loans-preapproval-invitation-mrp-button-prestaclip",
  // "loans-preapproval-request-confirmation",
  // "loans-preapproval-request-confirmation-clip",
  // "loans-preapproval-request-confirmation-mrp",
  // "loans-preapproval-request-confirmation-prestaclip",
  // "loans-preapproval-request-rejected-mrp",
  // "lockout-notification",
  // "lockout-warning",
  // "mdr-update",
  // "merchant-blacklist",
  // "merchant-referral-code",
  "merchant-referral-program",
  // "merchant-referral-qualification-failed",
  // "merchant-referral-qualification-successful",
  // "merchant-referral-reward",
  "multi-level-merchant-accept",
  "multi-level-merchant-request",
  // "one-cent-deposit-error",
  // "one-cent-deposit-rejected",
  // "one-cent-deposit-error",
  // "opt-blue-merchant-derogatory-response",
  "oxxo-payment",
  // "payment-request-cardholder-expiration",
  "payment-request-cardholder-pay",
  // "payment-request-cardholder-pay-a",
  // "payment-request-ch-paid-confirmation",
  // "payment-request-coupon",
  // "payment-request-expiration-alert",
  // "payment-request-expiration-alert-a",
  // "payment-request-expiration-alert-b",
  // "payment-request-expiration-alert-c",
  // "payment-request-expiration-confirmation",
  // "payment-request-merchant-confirmation",
  // "payment-request-merchant-confirmation-a",
  // "payment-request-merchant-paid-confirmation",
  // "payment-request-welcome",
  // "pymnts-topup-reconciliation-finance",
  // "pymnts-topup-reconciliation-prosa",
  // "reader-collection",
  // "reset-password",
  "sales-commi-password", // TODO: IMPORTANTE ICONO
  // "sales-commi-password-reset",
  // "sales-commi-rep-password",
  // "sales-order-confirmation",
  // "sales-order-delivered",
  // "sales-order-delivery-failure",
  //"sales-order-received",
  // "sales-order-rejected",
  // "sales-order-rejected-dostavista",
  // "sales-order-shipped",
  // "sales-order-shipped-99",
  // "sales-order-shipped-dostavista",
  // "sales-store-payment",
  // "shop-app-remarketing-1",
  // "shop-app-remarketing-1-B",
  // "shop-app-remarketing-1-C",
  // "shop-app-remarketing-1-D",
  // "shop-app-remarketing-1-E",
  // "shop-app-remarketing-1-F",
  // "shop-app-remarketing-2",
  // "shop-app-remarketing-2-B",
  // "shop-app-remarketing-2-C",
  // "shop-app-remarketing-3",
  // "shop-app-remarketing-3-C",
  // "shop-payment-refund",
  // "shop-payment-review",
  // "successful-password-reset",
  // "top-account-kpi",
  // "txn-codi",
  // "txn-payment",
  // "txn-payment-cancel",
  // "txn-payment-ctls",
  // "txn-payment-ecommerce",
  // "txn-payment-ecommerce-ch",
  // "txn-payment-ecommerce-receipt",
  // "txn-payment-no-cvm",
  // "txn-payment-pin",
  // "txn-payment-points",
  // "txn-payment-receipt",
  // "txn-payment-receipt-ctls",
  // "txn-payment-receipt-no-cvm",
  // "txn-payment-receipt-pin",
  // "txn-payment-refunded",
  // "txn-topup-consumer",
  // "txn-topup-consumer-pin",
  // "txn-topup-merchant",
  // "txn-topup-merchant-pin",
  "welcome-email",
  "welcome-email-agent",
  "welcome-email-generic",
  "welcome-email-generic-a",
  "welcome-email-generic-b",
  "welcome-email-generic-video",
  "welcome-email-leads",
  "welcome-email-leads-standard",
  "welcome-email-pro",
];

module.exports = list;
